{"name": "test_zixun[keqing0]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_case.test_web.Test_web object at 0x000002272A4CD710>\nkeqing = {'dao': '成都新闻', 'handle_value': 1, 'zhi': '北京新闻'}\n\n    @pytest.mark.parametrize(\"keqing\",Yaml(r\"data\\zuxun.yaml\").read_yaml())\n    def test_zixun(self,keqing):\n        ll=Po_1()\n>       ll.keli(keqing[\"handle_value\"],keqing[\"zhi\"],keqing[\"dao\"])\n\ntest_case\\test_web.py:43: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npo\\po_zixun.py:25: in keli\n    self.vilidate2(Po_1.keli7,zhi,dao)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <po.po_zixun.Po_1 object at 0x000002272A065BA8>\nloc = ('id', 'city_name'), zhi = '北京新闻', dao = '成都新闻'\n\n    def vilidate2(self,loc,zhi,dao):\n>       assert self.location(loc).text==zhi or self.location(loc).text==dao\nE       AssertionError\n\nbase\\base.py:50: AssertionError"}, "parameters": [{"name": "keqing", "value": "{'handle_value': 1, 'zhi': '北京新闻', 'dao': '成都新闻'}"}], "start": 1654745052824, "stop": 1654745079342, "uuid": "697e4ac7-a4ef-469d-b26b-9ced05729a96", "historyId": "82ff7de3eca2d200354bd4762d488924", "testCaseId": "c6082ccdbbbf16aa077e2590537384dc", "fullName": "test_case.test_web.Test_web#test_zixun", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_web"}, {"name": "subSuite", "value": "Test_web"}, {"name": "host", "value": "DESKTOP-0S9DG3S"}, {"name": "thread", "value": "7816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_web"}]}